name: Auth.APP
version: 0.1.10
description: Authentication application for mango services.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/auth
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers:
dependencies:
  mango_ui: '^1.0.3'
  mango_secure: '^1.0.5'